### PR TITLE
Feature/add tag

### PR DESCRIPTION
**Pull request by changhyuni**

### CODE REVIEW

**Comment by changhyuni** [comment]
atlantis plan -d eks/dev/network

**Comment by changhyuni** [comment]
Ran Plan for dir: `eks/dev/network` workspace: `default`

<details><summary>Show Output</summary>

```diff
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
~ update in-place

Terraform will perform the following actions:

  # module.vpc.aws_subnet.private[0] will be updated in-place
~ resource "aws_subnet" "private" {
        id                                             = "subnet-091ad38bf787f4737"
      ~ tags                                           = {
            "Name"                                        = "dev-cacoabank-vpc-private-ap-northeast-2a"
          + "atlantis"                                    = "true"
            "kubernetes.io/cluster/dev-cacoabank-cluster" = "shared"
            "kubernetes.io/role/internal-elb"             = "1"
            "subnet_type"                                 = "private"
        }
      ~ tags_all                                       = {
          + "atlantis"                                    = "true"
            # (7 unchanged elements hidden)
        }
        # (19 unchanged attributes hidden)
    }

  # module.vpc.aws_subnet.private[1] will be updated in-place
~ resource "aws_subnet" "private" {
        id                                             = "subnet-0f4330f96c3dbcc88"
      ~ tags                                           = {
            "Name"                                        = "dev-cacoabank-vpc-private-ap-northeast-2b"
          + "atlantis"                                    = "true"
            "kubernetes.io/cluster/dev-cacoabank-cluster" = "shared"
            "kubernetes.io/role/internal-elb"             = "1"
            "subnet_type"                                 = "private"
        }
      ~ tags_all                                       = {
          + "atlantis"                                    = "true"
            # (7 unchanged elements hidden)
        }
        # (19 unchanged attributes hidden)
    }

  # module.vpc.aws_subnet.private[2] will be updated in-place
~ resource "aws_subnet" "private" {
        id                                             = "subnet-02c30e5492a316791"
      ~ tags                                           = {
            "Name"                                        = "dev-cacoabank-vpc-private-ap-northeast-2c"
          + "atlantis"                                    = "true"
            "kubernetes.io/cluster/dev-cacoabank-cluster" = "shared"
            "kubernetes.io/role/internal-elb"             = "1"
            "subnet_type"                                 = "private"
        }
      ~ tags_all                                       = {
          + "atlantis"                                    = "true"
            # (7 unchanged elements hidden)
        }
        # (19 unchanged attributes hidden)
    }

Plan: 0 to add, 3 to change, 0 to destroy.
```
</details>

* :arrow_forward: To **apply** this plan, comment:
  ```shell
  atlantis apply -d eks/dev/network
  ```
* :put_litter_in_its_place: To **delete** this plan and lock, click [here](http://atlantis.juneman.click/lock?id=changhyuni%252Ftest-atlatnis%252Feks%252Fdev%252Fnetwork%252Fdefault)
* :repeat: To **plan** this project again, comment:
  ```shell
  atlantis plan -d eks/dev/network
  ```
Plan: 0 to add, 3 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this Pull Request, comment:
  ```shell
  atlantis apply
  ```
* :put_litter_in_its_place: To **delete** all plans and locks from this Pull Request, comment:
  ```shell
  atlantis unlock
  ```

**Review by inerplat — APPROVED** [review]

**Comment by changhyuni** [comment]
atlantis apply

**Comment by changhyuni** [comment]
Ran Apply for dir: `eks/dev/network` workspace: `default`

<details><summary>Show Output</summary>

```diff
module.vpc.aws_subnet.private[1]: Modifying... [id=subnet-0f4330f96c3dbcc88]
module.vpc.aws_subnet.private[0]: Modifying... [id=subnet-091ad38bf787f4737]
module.vpc.aws_subnet.private[2]: Modifying... [id=subnet-02c30e5492a316791]
module.vpc.aws_subnet.private[1]: Modifications complete after 0s [id=subnet-0f4330f96c3dbcc88]
module.vpc.aws_subnet.private[2]: Modifications complete after 0s [id=subnet-02c30e5492a316791]
module.vpc.aws_subnet.private[0]: Modifications complete after 0s [id=subnet-091ad38bf787f4737]

Apply complete! Resources: 0 added, 3 changed, 0 destroyed.

Outputs:

private_subnets = [
  "subnet-091ad38bf787f4737",
  "subnet-0f4330f96c3dbcc88",
  "subnet-02c30e5492a316791",
]
public_subnets = [
  "subnet-01d84fceb34e8f448",
  "subnet-0fc91d711af4d058b",
  "subnet-06599082d353105e7",
]
vpc_id = "vpc-0ee5b601210858868"
```

</details>

**Comment by changhyuni** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `eks/dev/network` workspace: `default`

**Pull request merged**
